name: Cache node modules
description: This action caches node modules to speed up yarn installs in workflows

inputs:
  paths:
    description: 'Path(s) to node modules you want to cache'
    required: true
    default: |
      **/node_modules/

runs:
  using: 'composite'
  steps:
    - name: Get Node version
      shell: bash
      id: node-version
      run: |-
        echo "version=$(node -v)" >> $GITHUB_OUTPUT

    - name: Cache node_modules
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ inputs.paths }}
        key: node-modules-v1-${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
