name: Github - Create release
description: This action creates a Github release entry

inputs:
  github-token:
    description: Github token
    required: true
  name:
    description: Release name
    required: true
  body:
    description: Release body
    required: true

outputs:
  id:
    description: 'ID of the created release'

runs:
  using: 'node16'
  main: 'action.js'
